package `in`.hridayan.ashell.ai.domain.model

import kotlinx.serialization.Serializable

/**
 * Source of a correction suggestion.
 */
@Serializable
enum class CorrectionSource {
    /** Correction from the built-in command database */
    DATABASE,

    /** Correction from heuristic/pattern matching */
    HEURISTIC,

    /** Correction generated by the AI model */
    AI
}
