name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip wget coreutils

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -P $HOME
        unzip $HOME/commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk/cmdline-tools
        rm $HOME/commandlinetools-linux-7583922_latest.zip
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3"
      env:
        JAVA_HOME: ${{ runner.tool_cache }}/Java_11
        ANDROID_HOME: $HOME/android-sdk
        PATH: $HOME/android-sdk/cmdline-tools:$HOME/android-sdk/platform-tools:$PATH

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
