name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: reactivecircus/android-sdk-manager-action@v2
      with:
        api-level: 30  # Ganti dengan API level sesuai kebutuhan
        build-tools: 30.0.3  # Versi build tools yang dibutuhkan
        target: android-30  # Target SDK yang diperlukan untuk proyek kamu

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
