name: Build and Sign APK

on:
  push:
    branches:
      - test  # Change this to your branch name

jobs:
  build:
    name: Build and Sign APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p app
          echo "$KEYSTORE_BASE64" | base64 --decode > app/keystore.jks

      - name: Set Environment Variables
        run: |
          echo "KEYSTORE_PATH=app/keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Grant Execute Permission to Gradle
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Find Release APK
        run: echo "APK_PATH=$(find app/build/outputs/apk/release -name '*.apk' -print -quit)" >> $GITHUB_ENV

      - name: Install apksigner
        run: sudo apt-get update && sudo apt-get install -y apksigner

      - name: Sign APK
        run: |
          apksigner sign --ks "$KEYSTORE_PATH" \
          --ks-pass pass:"$KEYSTORE_PASSWORD" --key-pass pass:"$KEY_PASSWORD" \
          --out app-release-signed.apk "$APK_PATH"

      - name: Verify APK Signature
        run: apksigner verify --verbose --print-certs app-release-signed.apk

      - name: Upload Signed APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed-APK
          path: app-release-signed.apk